// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { CurrentData, CurrentResponse, PagesData, PagesResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class ConfigService {
    public static current<ThrowOnError extends boolean = false>(options?: Options<CurrentData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<CurrentResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/accessibilityreporter/api/v1/config/current',
            ...options
        });
    }
    
}

export class DirectoryService {
    public static pages<ThrowOnError extends boolean = false>(options?: Options<PagesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<PagesResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/accessibilityreporter/api/v1/pages',
            ...options
        });
    }
    
}