// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { CurrentData, CurrentResponse, PagesData, PagesResponse, CreateData, RunsData, RunsResponse, SitesData, SitesResponse, TrendData, TrendResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class ConfigService {
    public static current<ThrowOnError extends boolean = false>(options?: Options<CurrentData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<CurrentResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/accessibilityreporter/api/v1/config/current',
            ...options
        });
    }

}

export class DirectoryService {
    public static pages<ThrowOnError extends boolean = false>(options?: Options<PagesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<PagesResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/accessibilityreporter/api/v1/pages',
            ...options
        });
    }

}

export class TestRunService {
    public static create<ThrowOnError extends boolean = false>(options: Options<CreateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/accessibilityreporter/api/v1/test-run/{contentId}/{culture}/{contentHash}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }

    public static runs<ThrowOnError extends boolean = false>(options: Options<RunsData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<RunsResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/accessibilityreporter/api/v1/test-runs/{contentId}/{culture}',
            ...options
        });
    }

}

export class SiteHistoryService {
    public static sites<ThrowOnError extends boolean = false>(options?: Options<SitesData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<SitesResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/accessibilityreporter/api/v1/site-history/sites',
            ...options
        });
    }

    public static trend<ThrowOnError extends boolean = false>(options: Options<TrendData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<TrendResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/accessibilityreporter/api/v1/site-history/{rootContentId}/trend',
            ...options
        });
    }

}
