// This file is auto-generated by @hey-api/openapi-ts

export type AccessibilityReporterAppSettings = {
    apiUrl: string;
    testBaseUrl: string;
    runTestsAutomatically: boolean;
    includeIfNoTemplate: boolean;
    maxPages: number;
    userGroups: Array<string>;
    testsToRun: Array<string>;
    excludedDocTypes: Array<string>;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NodeSummaryReadable = {
    readonly guid: string;
    readonly id: number;
    readonly name: string;
    readonly docTypeAlias: string;
    url: string;
};

export type NodeSummaryWritable = {
    url: string;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type TestRun = {
    contentId: string;
    runCompleted: string;
    score: number;
    resultPayload: string;
};

export type CurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/accessibilityreporter/api/v1/config/current';
};

export type CurrentErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CurrentResponses = {
    /**
     * OK
     */
    200: AccessibilityReporterAppSettings;
};

export type CurrentResponse = CurrentResponses[keyof CurrentResponses];

export type PagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/accessibilityreporter/api/v1/pages';
};

export type PagesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PagesResponses = {
    /**
     * OK
     */
    200: Array<NodeSummaryReadable>;
};

export type PagesResponse = PagesResponses[keyof PagesResponses];

export type CreateData = {
    body?: string;
    path: {
        contentId: string;
    };
    query?: never;
    url: '/umbraco/accessibilityreporter/api/v1/test-run/{contentId}';
};

export type CreateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type RunsData = {
    body?: never;
    path: {
        contentId: string;
    };
    query?: never;
    url: '/umbraco/accessibilityreporter/api/v1/test-runs/{contentId}';
};

export type RunsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type RunsResponses = {
    /**
     * OK
     */
    200: Array<TestRun>;
};

export type RunsResponse = RunsResponses[keyof RunsResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44312' | (string & {});
};