// This file is auto-generated by @hey-api/openapi-ts

export type AccessibilityReporterAppSettings = {
    apiUrl: string;
    testBaseUrl: string;
    siteBaseUrls: {
        [key: string]: string;
    };
    runTestsAutomatically: boolean;
    includeIfNoTemplate: boolean;
    maxPages: number;
    userGroups: Array<string>;
    testsToRun: Array<string>;
    excludedDocTypes: Array<string>;
};

export type NodeSummaryReadable = {
    readonly guid: string;
    id: number;
    name: string;
    readonly docTypeAlias: string;
    url: string;
    rootId: string;
    rootName: string;
};

export type NodeSummaryWritable = {
    id: number;
    name: string;
    url: string;
    rootId: string;
    rootName: string;
};

export type CurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/accessibilityreporter/api/v1/config/current';
};

export type CurrentErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CurrentResponses = {
    /**
     * OK
     */
    200: AccessibilityReporterAppSettings;
};

export type CurrentResponse = CurrentResponses[keyof CurrentResponses];

export type PagesData = {
    body?: never;
    path?: never;
    query?: {
        culture?: string;
    };
    url: '/umbraco/accessibilityreporter/api/v1/pages';
};

export type PagesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PagesResponses = {
    /**
     * OK
     */
    200: Array<NodeSummaryReadable>;
};

export type PagesResponse = PagesResponses[keyof PagesResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44312' | (string & {});
};