// This file is auto-generated by @hey-api/openapi-ts

export type AccessibilityReporterAppSettings = {
    apiUrl: string;
    testBaseUrl: string;
    runTestsAutomatically: boolean;
    includeIfNoTemplate: boolean;
    maxPages: number;
    userGroups: Array<string>;
    testsToRun: Array<string>;
    excludedDocTypes: Array<string>;
};

export type NodeSummaryReadable = {
    readonly guid: string;
    readonly id: number;
    readonly name: string;
    readonly docTypeAlias: string;
    url: string;
};

export type NodeSummaryWritable = {
    url: string;
};

export type CurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/accessibilityreporter/api/v1/config/current';
};

export type CurrentErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CurrentResponses = {
    /**
     * OK
     */
    200: AccessibilityReporterAppSettings;
};

export type CurrentResponse = CurrentResponses[keyof CurrentResponses];

export type PagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/accessibilityreporter/api/v1/pages';
};

export type PagesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PagesResponses = {
    /**
     * OK
     */
    200: Array<NodeSummaryReadable>;
};

export type PagesResponse = PagesResponses[keyof PagesResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44312' | (string & {});
};

export type AiViolationInfo = {
    id: string;
    impact: string;
    help: string;
    nodeCount: number;
};

export type AiSummaryRequest = {
    pageUrl: string;
    pageName: string;
    score: number;
    violations: Array<AiViolationInfo>;
    incompleteCount: number;
};

export type AiSummaryResponseModel = {
    available: boolean;
    summary?: string | null;
};

export type AiSummaryData = {
    body: AiSummaryRequest;
    path?: never;
    query?: never;
    url: '/umbraco/accessibilityreporter/api/v1/ai/summary';
};

export type AiSummaryErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type AiSummaryResponses = {
    /**
     * OK
     */
    200: AiSummaryResponseModel;
};

export type AiSummaryApiResponse = AiSummaryResponses[keyof AiSummaryResponses];

export type AiSitePageInfo = {
    name: string;
    url: string;
    score: number;
    violationCount: number;
};

export type AiSiteViolationSummary = {
    id: string;
    impact: string;
    help: string;
    totalOccurrences: number;
    affectedPages: number;
};

export type AiSiteSummaryRequest = {
    averageScore: number;
    totalPages: number;
    totalViolations: number;
    pages: Array<AiSitePageInfo>;
    mostCommonViolations: Array<AiSiteViolationSummary>;
};

export type AiSiteSummaryData = {
    body: AiSiteSummaryRequest;
    path?: never;
    query?: never;
    url: '/umbraco/accessibilityreporter/api/v1/ai/site-summary';
};

export type AiSiteSummaryErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type AiSiteSummaryResponses = {
    /**
     * OK
     */
    200: AiSummaryResponseModel;
};

export type AiSiteSummaryApiResponse = AiSiteSummaryResponses[keyof AiSiteSummaryResponses];

export type AiAccessibilityStatementRequest = {
    websiteName: string;
    websiteUrl: string;
    organisationName: string;
    averageScore: number;
    totalPages: number;
    totalViolations: number;
    pages: Array<AiSitePageInfo>;
    mostCommonViolations: Array<AiSiteViolationSummary>;
};

export type AiAccessibilityStatementData = {
    body: AiAccessibilityStatementRequest;
    path?: never;
    query?: never;
    url: '/umbraco/accessibilityreporter/api/v1/ai/accessibility-statement';
};

export type AiAccessibilityStatementErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type AiAccessibilityStatementResponses = {
    /**
     * OK
     */
    200: AiSummaryResponseModel;
};

export type AiAccessibilityStatementApiResponse = AiAccessibilityStatementResponses[keyof AiAccessibilityStatementResponses];

export type AiManualTestsRequest = {
    pageUrl: string;
    pageName: string;
    pageHtml: string;
    score: number;
    violations: Array<AiViolationInfo>;
    incompleteCount: number;
};

export type AiManualTestsData = {
    body: AiManualTestsRequest;
    path?: never;
    query?: never;
    url: '/umbraco/accessibilityreporter/api/v1/ai/manual-tests';
};

export type AiManualTestsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type AiManualTestsResponses = {
    /**
     * OK
     */
    200: AiSummaryResponseModel;
};

export type AiManualTestsApiResponse = AiManualTestsResponses[keyof AiManualTestsResponses];
