<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Umbraco.Cms.Core" Version="17.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AccessibilityReporter.Core\AccessibilityReporter.Core.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <PackageId>Umbraco.Community.AccessibilityReporter.Services</PackageId>
        <IncludeSymbols>True</IncludeSymbols>
        <Title>Accessibility Reporter Services</Title>
        <Description>Accessibility Reporter for Umbraco helps you to make your website accessible.</Description>
        <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/mattbegent/umbraco-accessibility-reporter</RepositoryUrl>
        <PackageProjectUrl>https://github.com/mattbegent/umbraco-accessibility-reporter</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Copyright>Matt Begent</Copyright>
        <PackageIcon>logo.png</PackageIcon>
        <PackageReleaseNotes>Accessibility Reporter for Umbraco 16+.</PackageReleaseNotes>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

     <!-- Readme, Logo etc needed for Nuget Package -->
    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\logos\logo.png" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
