import { LitElement, css, html, customElement, property, unsafeHTML, PropertyValues } from "@umbraco-cms/backoffice/external/lit";
import { marked } from 'marked';
import AiSummaryState from "../Enums/ai-summary-state";
import { generalStyles } from "../Styles/general";

@customElement('ar-ai-summary')
export class ARAiSummaryElement extends LitElement {

	@property({ attribute: false })
	state: AiSummaryState = AiSummaryState.Idle;

	@property()
	summary: string = '';

	@property({ attribute: false })
	onGenerate: () => void = () => {};

	@property()
	idleDescription: string = 'Generate an AI-powered summary of the accessibility issues.';

	@property({ type: Boolean })
	autoGenerate: boolean = false;

	#hasAutoGenerated = false;

	protected updated(changedProperties: PropertyValues): void {
		super.updated(changedProperties);
		if (this.autoGenerate && !this.#hasAutoGenerated && this.state === AiSummaryState.Idle) {
			this.#hasAutoGenerated = true;
			this.onGenerate();
		}
	}

	render() {
		if (this.state === AiSummaryState.Unavailable) {
			return html``;
		}

		return html`
			<uui-box>
				<div slot="headline" class="c-title__group">
					<div class="c-circle">
						<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
							<g fill="none" fill-rule="evenodd">
								<path d="M24 0v24H0V0zM12.593 23.258l-.011.002-.071.035-.02.004-.014-.004-.071-.035q-.016-.005-.024.005l-.004.01-.017.428.005.02.01.013.104.074.015.004.012-.004.104-.074.012-.016.004-.017-.017-.427q-.004-.016-.017-.018m.265-.113-.013.002-.185.093-.01.01-.003.011.018.43.005.012.008.007.201.093q.019.005.029-.008l.004-.014-.034-.614q-.005-.018-.02-.022m-.715.002a.02.02 0 0 0-.027.006l-.006.014-.034.614q.001.018.017.024l.015-.002.201-.093.01-.008.004-.011.017-.43-.003-.012-.01-.01z"/>
								<path fill="currentColor" d="M5.827 13.004a.19.19 0 0 1 .346 0l.17.371a8.7 8.7 0 0 0 3.3 3.638l.265.155a.181.181 0 0 1 0 .316l-.265.155a8.7 8.7 0 0 0-3.3 3.638l-.17.372a.19.19 0 0 1-.346 0l-.17-.372a8.7 8.7 0 0 0-3.3-3.638l-.265-.155a.181.181 0 0 1 0-.316l.265-.155a8.7 8.7 0 0 0 3.47-4.01m.17 3.486-.175.206q-.187.21-.385.41l-.2.198-.027.024.227.223.195.203.19.208.175.205.175-.205q.187-.21.385-.411l.227-.223-.027-.024q-.203-.195-.395-.4l-.19-.208zm8.476-13.76a.331.331 0 0 1 .605 0l.15.336.148.314.195.39.226.42.112.196a15.2 15.2 0 0 0 3.895 4.437l.427.317a15 15 0 0 0 1.383.878.317.317 0 0 1 0 .553 15 15 0 0 0-1.082.67l-.36.251a15.2 15.2 0 0 0-4.263 4.71l-.131.232q-.212.382-.402.775l-.147.314-.15.336a.331.331 0 0 1-.606 0l-.15-.336-.148-.314-.196-.39-.225-.42-.113-.196a15.2 15.2 0 0 0-3.894-4.437l-.428-.316a15 15 0 0 0-1.382-.88.317.317 0 0 1 0-.552 15 15 0 0 0 1.082-.669l.36-.252a15.2 15.2 0 0 0 4.262-4.71l.132-.232q.212-.38.402-.775l.147-.314zm.302 3.615a17.2 17.2 0 0 1-3.663 3.95 17.2 17.2 0 0 1 3.663 3.95 17.2 17.2 0 0 1 3.663-3.95 17.2 17.2 0 0 1-3.663-3.95"/>
							</g>
						</svg>
					</div>
					<h2 class="c-title">AI Summary</h2>
				</div>
				${this.state === AiSummaryState.Idle ? html`
					<p>${this.idleDescription}</p>
					<uui-button look="primary" color="default" @click="${this.onGenerate}" label="Generate AI summary of accessibility issues">Generate AI Summary</uui-button>
				` : null}
				${this.state === AiSummaryState.Loading ? html`
					<uui-loader-bar animationDuration="1.5" style="color: #443b52"></uui-loader-bar>
					<p>Generating summary&hellip;</p>
				` : null}
				${this.state === AiSummaryState.Done ? html`
					<div class="c-ai-summary">
						${unsafeHTML(marked.parse(this.summary) as string)}
					</div>
					<uui-button look="secondary" color="default" @click="${this.onGenerate}" label="Regenerate AI summary of accessibility issues">Regenerate Summary</uui-button>
				` : null}
				${this.state === AiSummaryState.Errored ? html`
					<p>An error occurred generating the summary. Please ensure Umbraco.AI is configured with a default chat profile.</p>
					<uui-button look="secondary" color="default" @click="${this.onGenerate}" label="Retry generating AI summary">Try again</uui-button>
				` : null}
			</uui-box>
		`;
	}

	static styles = [
		generalStyles,
		css`
			:host {
				display: block;
			}

			.c-ai-summary {
				background: var(--uui-color-surface-alt, #f4f4f4);
				border-radius: var(--uui-border-radius, 4px);
				padding: 16px;
				margin-bottom: 12px;
				font-size: 16px;
				line-height: 1.6;
				max-width: 900px;
			}

			.c-ai-summary h1 {
				margin-top: 0;
			}

			.c-ai-summary p:first-child {
				margin-top: 0;
			}

			.c-ai-summary p:last-child {
				margin-bottom: 0;
			}

			.c-ai-summary ul,
			.c-ai-summary ol {
				padding-left: 1.5em;
				margin: 0.5em 0;
			}

			.c-ai-summary li {
				margin-bottom: 0.25em;
			}

			.c-ai-summary strong {
				font-weight: 600;
			}
    	`,
	];
}

declare global {
	interface HTMLElementTagNameMap {
		'ar-ai-summary': ARAiSummaryElement;
	}
}
