<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NPoco" Version="6.1.0" />
    <PackageReference Include="Umbraco.Cms.Core" Version="17.2.1" />
    <PackageReference Include="Umbraco.Cms.Infrastructure" Version="17.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccessibilityReporter.Core\AccessibilityReporter.Core.csproj" />
  </ItemGroup>

</Project>
