<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NPoco" Version="5.7.1" />
    <PackageReference Include="Umbraco.Cms.Core" Version="16.3.4" />
    <PackageReference Include="Umbraco.Cms.Infrastructure" Version="16.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccessibilityReporter.Core\AccessibilityReporter.Core.csproj" />
  </ItemGroup>

</Project>
